export type DetailedSection = {
  title: string;
  summary: string;
  points: string[];
};

export const detailedCropContent: Record<string, DetailedSection[]> = {
  rice: [
    { title: 'Where and how rice is grown', summary: 'Rice is grown in irrigated, rainfed lowland, upland, flood-prone, coastal, and hill systems. The variety and establishment method must match the local ecology.', points: ['Major belts include eastern and coastal India, north-western irrigated plains, and southern India.', 'Choose varieties for the local season and for drought, flood, salinity, or upland conditions where those stresses occur.', 'Transplanting and direct seeding are both used; nursery hygiene and timely field preparation matter in either system.'] },
    { title: 'Soil, water, and nutrition', summary: 'Moisture-retentive, fertile soil and careful water management support the crop, but unnecessary flooding is not always required.', points: ['Use soil testing and integrated nutrient management; combine suitable organic inputs with mineral nutrients.', 'Avoid excessive nitrogen because it can increase lodging and some pest and disease problems.', 'Protect panicle initiation, flowering, and grain filling from water stress; drain before harvest where appropriate.', 'Early weed control is especially important in direct-seeded rice.'] },
    { title: 'Harvest and storage', summary: 'Timely harvest and uniform drying protect grain quality and reduce storage losses.', points: ['Harvest when most grains are mature and panicles have changed colour rather than leaving the crop too long in the field.', 'Dry grain promptly and uniformly before storage.', 'Keep grain, seed, and storage areas clean and protected from moisture and rodents.'] },
  ],
  tomato: [
    { title: 'Season and site selection', summary: 'Tomato is widely grown in irrigated vegetable belts, but season, disease pressure, and market needs vary by region.', points: ['Use well-drained soil with organic matter and good sunlight; waterlogging increases root and wilt problems.', 'Excess heat, cold, or humidity can affect flowering, fruit set, and fruit quality.', 'Avoid repeated tomato, chilli, or brinjal cultivation in the same field where disease pressure is high.'] },
    { title: 'Nursery and crop care', summary: 'A clean, vigorous nursery is the first protection against many early crop failures.', points: ['Use quality seed from an authorized source and a clean, well-drained nursery.', 'Avoid overcrowding and excess irrigation; harden healthy seedlings before transplanting.', 'Keep moisture even during flowering and fruit enlargement; irregular wet-dry cycles can contribute to cracking.', 'Support indeterminate plants, maintain airflow, and remove diseased material from the field.'] },
    { title: 'Harvest and quality', summary: 'Harvest maturity should match the market and transport distance.', points: ['Harvest at mature-green, breaker, turning, or red-ripe stage as required by the buyer.', 'Handle fruit gently, keep it shaded, sort damaged fruit, and use clean ventilated crates.', 'Remove damaged fruit and plant debris to reduce carry-over of pests and diseases.'] },
  ],
  cotton: [
    { title: 'Cotton zones and establishment', summary: 'Cotton is grown in northern, central, and southern zones under both rainfed and irrigated conditions.', points: ['Use locally recommended Bt or non-Bt varieties or hybrids and certified seed.', 'Follow the regional sowing window, suitable plant stand, current refuge guidance, and crop rotation advice.', 'A warm, frost-free season and well-drained soil are important; both waterlogging and prolonged drought reduce performance.'] },
    { title: 'Water, nutrition, and canopy', summary: 'Cotton needs balanced growth from squaring through boll development, not excessive leafy growth.', points: ['Use soil testing and zone-specific recommendations; balance nitrogen with phosphorus, potassium, and diagnosed micronutrients.', 'Protect establishment, flowering, and boll development from severe water stress.', 'Keep the field weed-free during early competition and remove volunteer cotton and residues where advised.', 'Avoid late excessive nitrogen and maintain an open, aerated canopy.'] },
    { title: 'Boll opening and picking', summary: 'Clean, dry picking and residue management protect fibre quality and reduce carry-over pests.', points: ['Pick fully opened, dry bolls at regular intervals.', 'Separate stained or damp kapas and keep harvested cotton away from soil and contamination.', 'Timely crop termination and residue destruction form part of pink bollworm management in relevant zones.'] },
  ],
  coconut: [
    { title: 'Planting and palm establishment', summary: 'Coconut is a perennial crop, so site and planting-material decisions affect the plantation for many years.', points: ['Use healthy, true-to-type seedlings from a reliable nursery.', 'Choose spacing, pits, and intercrops for the local soil, cultivar, drainage, and wind exposure.', 'Stake and protect young palms from grazing and mechanical damage.'] },
    { title: 'Water, soil, and canopy care', summary: 'Moisture conservation is useful, but prolonged standing water is damaging.', points: ['Young palms need reliable moisture; mature palms benefit from mulch and supplemental irrigation during dry periods where water is available.', 'Maintain a weed-managed basin without damaging surface roots and use clean organic mulch.', 'Use soil and leaf diagnosis where available; do not copy a fertilizer schedule from another district.', 'Remove dead fronds and diseased material safely, and maintain compatible intercrops with adequate light.'] },
    { title: 'Palm health and harvest', summary: 'Regular crown observation helps identify problems before they become difficult to manage.', points: ['Inspect the crown for rhinoceros beetle, red palm weevil, whitefly, caterpillar, and bud-rot symptoms.', 'Harvest at the maturity needed for tender nut, copra, oil, or other products.', 'Grade nuts and dry copra hygienically; protect stored products from moisture, mould, and rodents.'] },
  ],
  chilli: [
    { title: 'Season, soil, and nursery', summary: 'Chilli is grown as a spice and vegetable crop, with strong regional differences in season and disease pressure.', points: ['Use well-drained soil, warm conditions, and adequate sunlight; avoid waterlogging and excessive humidity.', 'Raise healthy seedlings in a clean nursery using quality seed and locally recommended varieties.', 'Harden seedlings before transplanting and do not plant visibly diseased seedlings.'] },
    { title: 'Water, nutrition, and canopy', summary: 'Steady moisture and a well-aired canopy help through flowering and fruit development.', points: ['Maintain even moisture during establishment, flowering, and fruit development.', 'Base nutrition on soil testing and crop purpose; avoid excess nitrogen and diagnose micronutrient deficiency before correction.', 'Control weeds early, remove volunteer solanaceous plants, and avoid a dense canopy.', 'Avoid overhead irrigation that keeps foliage wet for long periods where disease risk is high.'] },
    { title: 'Fruit protection and drying', summary: 'Frequent observation is important because thrips, mites, vectors, and fruit diseases can spread quickly.', points: ['Inspect growing points, flowers, and fruit regularly; conserve natural enemies.', 'Hand-pick damaged fruit and use sanitation and monitoring before considering treatment.', 'Harvest green, mature-red, or fully dried fruit according to market use; dry on clean surfaces and store in moisture-proof conditions.'] },
  ],
  arecanut: [
    { title: 'Plantation and site selection', summary: 'Arecanut needs a warm, humid environment, fertile well-drained soil, and protection from severe drought and waterlogging.', points: ['Important production areas include Karnataka, Kerala, Assam, West Bengal, Tamil Nadu, Meghalaya, and Tripura.', 'Select healthy seedlings from a reliable source and use locally recommended spacing and pit preparation.', 'On sloping land, use contour measures and soil-moisture conservation to reduce erosion.'] },
    { title: 'Moisture, shade, and nutrition', summary: 'Young palms need regular moisture; mature plantations benefit from mulch and careful drainage.', points: ['Provide shade and support to young palms and drain excess water promptly during heavy rain.', 'Use soil testing and local CPCRI or state recommendations for nutrition; exact quantities are not universal.', 'Keep basins weed-managed without root injury, maintain suitable shade, and avoid stem or root-zone damage.', 'Compatible intercrops may be possible where the local recommendation supports them.'] },
    { title: 'Disease watch and processing', summary: 'Wet-weather diseases and gradual yellowing require early observation and local diagnosis.', points: ['Watch for Koleroga/fruit rot, root grub, inflorescence damage, mites, and yellow-leaf or wilt syndromes.', 'Collect and dispose of fallen diseased nuts, improve drainage and sanitation, and seek local diagnosis before removing palms.', 'Harvest by intended product, sort damaged nuts, and dry or process promptly in clean conditions.'] },
  ],
  coffee: [
    { title: 'Arabica, Robusta, and site', summary: 'Coffee is grown mainly in Karnataka, Kerala, and Tamil Nadu, with additional production in eastern and north-eastern hill areas.', points: ['Arabica generally suits cooler, higher locations; Robusta generally suits warmer, more humid locations. These are broad Coffee Board ranges, not rigid thresholds.', 'Deep, well-drained, organic-matter-rich, slightly acidic soil and managed shade support the crop.', 'Use contours, terraces, ground cover, and wind protection on slopes and exposed sites.'] },
    { title: 'Nursery, shade, and water', summary: 'Coffee quality and productivity depend on a healthy root environment and a well-managed shade canopy.', points: ['Use healthy planting material from an authorized source and harden nursery plants before field planting.', 'Conserve moisture with mulch, contour trenches, and managed ground cover; avoid runoff and waterlogging.', 'Regulate temporary and permanent shade, prune and desucker according to local Coffee Board or CCRI guidance.', 'Use soil and leaf analysis to guide acidity and nutrient correction; exact fertilizer quantities need regional review.'] },
    { title: 'Berry development and quality', summary: 'Harvest and processing decisions strongly influence coffee quality.', points: ['Scout for berry borer, white stem borer, leaf rust, berry diseases, and root diseases.', 'Pick ripe red cherries selectively where quality is the priority and remove fallen or leftover berries.', 'Keep cherries shaded and process promptly; dry parchment or processed coffee uniformly on clean surfaces and store in clean, odour-free conditions.'] },
  ],
};
